plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    // Loom automatically adds essential maven repositories for Minecraft and libraries
}

loom {
    //accessWidenerPath = file("src/main/resources/allmod.accesswidener")
    mods {
        "ww-all" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    //mappings loom.officialMojangMappings()
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    def props = [
            version        : project.version,
            loader_version : project.loader_version,
            minecraft_version: project.minecraft_version,
            fabric_version : project.fabric_version
    ]
    props.each { k, v -> inputs.property(k, v) }
    filesMatching("fabric.mod.json") {
        expand(props)
    }
}
def javaVersion = (project.java_version as int)

tasks.withType(JavaCompile).configureEach {
    it.options.release = javaVersion
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

jar {
    inputs.property "projectName", project.name
    from("LICENSE") {
        rename { "${it}_${project.name}" }
    }
}
