#PROJECT STUFF
org.gradle.jvmargs=-Xmx2G
mod_version=1.00
maven_group=ww
archives_base_name=smoothiemod
# check this on https://modmuss50.me/fabric.html

#modmuss50 output (rename fabric_api to fabric_)
minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

fabric_version=0.145.1+26.1
java_version = 25

